apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sample-model-training-workflow
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple model training example.
spec:
  entrypoint: sample_job
  templates:
  - name: sample-workflow
    container:
      image: sample_job
